[package]
name = "dahl-randompartition"
version = "0.1.0"
authors = ["David B. Dahl <dahl@stat.byu.edu>"]
edition = "2018"
description = "An efficient representation of a set partition."
homepage = "https://dahl.byu.edu"
license = "MIT OR Apache-2.0"

[dependencies]
dahl-partition = { git="https://dahl-git.byu.edu/dahl/rust-dahl-partition.git" }
#dahl-partition = { path="/home/dahl/docs/devel/rust-dahl-partition" }
dahl-salso = { git="https://dahl-git.byu.edu/dahl/rust-dahl-salso.git" }
#dahl-salso = { path="/home/dahl/docs/devel/rust-dahl-salso" }
rand = "0.7.2"
statrs = "0.12.0"
